### ISSUE TITLE
small typo 

### ISSUE THREAD

**Issue by sklarzykm** [Edgeware-Network/Edgeware-Website#8]
<img width="1090" alt="Screen Shot 2021-03-13 at 2 17 50 PM" src="https://user-images.githubusercontent.com/80607287/111054930-85a5b380-843e-11eb-9fc0-96e940e26910.png">

**Comment by johny** [comment]
Thanks @sklarzykm  for reporting the issue.
Fixed by https://github.com/Edgeware-Network/Edgeware-Website/pull/9
